ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_national.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_al.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_al
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ak.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ak
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_az.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_az
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ar.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ar
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ca.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ca
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_co.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_co
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ct.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ct
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_de.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_de
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_dc.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_dc
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_fl.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_fl
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ga.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ga
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_hi.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_hi
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_id.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_id
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_il.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_il
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_in.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_in
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ia.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ia
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ks.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ks
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ky.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ky
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_la.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_la
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_me.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_me
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_md.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_md
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ma.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ma
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_mi.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_mi
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_mn.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_mn
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ms.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ms
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_mo.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_mo
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_mt.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_mt
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ne.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ne
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nv.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nv
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nh.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nh
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nj.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nj
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nm.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nm
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ny.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ny
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nc.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nc
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_nd.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_nd
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_oh.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_oh
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ok.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ok
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_or.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_or
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_pa.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_pa
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ri.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ri
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_sc.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_sc
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_sd.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_sd
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_tn.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_tn
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_tx.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_tx
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_ut.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_ut
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_vt.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_vt
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_va.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_va
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_wa.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_wa
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_wv.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_wv
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_wi.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_wi
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_wy.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_wy
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_as.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_as
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_gu.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_gu
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_mp.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_mp
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_pr.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_pr
ogr2ogr -overwrite -f "GeoJSON" geojson_territories/utility_territories_vi.geojson PG:"host=127.0.0.1 dbname=makeutils" utility_territories_vi
